services:
  db:
    image: postgres:17-alpine
    container_name: bookshelf-db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - bookshelf_postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:17-alpine
    container_name: bookshelf-db-test
    restart: always
    ports:
      - "${POSTGRES_PORT_TEST}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}-test
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: bookshelf-api
    ports:
      - '3000:3000'
    depends_on:
      - db
      - db-test
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      DATABASE_TEST_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db-test:${POSTGRES_PORT_TEST}/${POSTGRES_DB}-test?schema=public
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  bookshelf_postgres_data:
